experiment:
    project_name: maskgit
    name: run1
    max_train_examples: 10000000
    save_every: 1000
    eval_every: 500
    sample_every: 10000000
    log_every: 500
    log_level: info
    resume_path_from_checkpoint: null


codebook:
        codebook_dim: 32
        beta : 0.25
        codebook_size: 8192

vitvqgan:
    checkpoint : outputs/vitvqgan/checkpoints/VitVQGAN.pt
    transformer:
        dim : 512
        patch_size : 8
        n_heads : 8
        d_head : 64
        depth : 6
        dropout : 0.0
        mlp_dim: 2048

model:
    name: maskgit
    dim : 768
    n_heads : 12
    d_head : 64
    depth : 16
    mult : 8
    dropout : 0.0

dataset:
    name: coco
    params:
        train_path:   /home/pranoy/datasets/coco2017
        val_path: null
        num_workers: 4
        pin_memory: True
        batch_size: 8
        persistent_workers: True
        shuffle : True
        train_test_split : 0.9
    preprocessing:
        resolution: 256
        center_crop: False
        random_flip: True
        random_crop: True
        mean : null
        std : null
        scale : 1.0

optimizer:
    name: adam
    params: 
        learning_rate: 0.0001
        beta1: 0.9
        beta2: 0.96
        weight_decay: 0.0
        epsilon: 1e-8

lr_scheduler:
    name: cosine_with_warmup
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 4000
        decay_steps: null

training:
    gradient_accumulation_steps: 32
    mixed_precision: "no"
    seed: 42
    num_epochs: 200
    max_grad_norm: null
