experiment:
    project_name: muse_vqgan
    exp_name: resume_run
    num_train_samples: 1000000000
    save_every: 2000
    eval_every: null
    sample_every: 2000
    log_every: 100
    log_level: info
    resume_path_from_checkpoint: /home/pranoy/code/scratch_experiments/outputs/muse_vqgan/checkpoints/muse_vqgan_more_depth.pt


codebook:
        codebook_dim: 32
        beta : 0.25
        codebook_size: 8192

vitvqgan:
    checkpoint : outputs/vitvqgan/checkpoints/VitVQGAN.pt
    transformer:
        dim : 512
        patch_size : 8
        n_heads : 8
        d_head : 64
        depth : 6
        dropout : 0.
        mlp_dim: 2048

model:
    name: muse_vqgan
    dim : 1024
    encoder:
        type: clip
        name : openai/clip-vit-large-patch14
        max_length : 77
    decoder:
        n_heads : 16
        d_head : 64
        depth : 16
        mult : 6
        dropout : 0.0

dataset:
    name: webdataset
    params:
        train_path:  http://192.168.2.8:8000/mscoco/{00000..00059}.tar
        val_path: null
        num_workers: 4
        pin_memory: True
        batch_size: 1
        persistent_workers: True
        shuffle : False
        train_test_split : 0.9
    preprocessing:
        resolution: 256
        center_crop: False
        random_flip: False
        random_crop: True
        mean : null
        std : null
        scale : 1.0

optimizer:
    name: adamw
    params: 
        learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01

lr_scheduler:
    name: constant_with_warmup
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 1000
        decay_steps: null

training:
    gradient_accumulation_steps: 16
    mixed_precision: "no"
    seed: 42
    num_epochs: 200
    max_grad_norm: null
